### ISSUE TITLE
Sound and Music FX

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/mindmazer#7]
We need the following **SOUNDS** for the game:
- Button click (~1sec) (Tron electric sound)
- Jump sound, 3 variants (~0.5-1sec) (tiny little voice)
- "You died" sound  (~2sec) (Something with an echo, no voice but some noise)
- "Game Over" Sound (~3-4sec)
- Collect life sound (~1sec) (Like in Mario or Zelda)
- Level complete sound (~2sec) (Success, yey, but in Tron style!)
- Preview level sound (Mystery!)
- Hide/obscure level sound (fog incoming, should be kinda mysterious as well)
- *Gain percentage/progress sound (~0.3sec) (OPTIONAL!, maybe not required)*

We need the following **MUSIC**:
- **Main Menu Theme** (Calm, dark and Tron)
- **Level Theme Calm** (should be ~1min length so we can loop it), will be played when percentage is < 40%
- **Level Theme Progress** (should be ~2min length so we can loop it), will be played when percentage is between 40% and 80%
- **Level Theme Almost Finished** (should be ~30secs length so we can loop it), will be played when percentage is over 80%
- **Game Over Screen** (Shouldn't be sad music, should be similar to main menu but with a beat)

## Contribution Details

All sounds and music should be provided as .ogg format to save diskspace. All tracks should have short names like "button_click.ogg", names should be all lowercase and separated via underscores _.
Put all sounds into `android/assets/sounds` and all music into `android/assets/music`

**Comment by bitbrain** [comment]
I uploaded a new version 0.8.0, including your sound effects for most of the parts.

https://www.dropbox.com/s/b3egnzovoca5ftq/mindmazer-0.8.0.zip?dl=0

 I noticed that some additional sounds would be nice:
- **respawn** after the player dies he respawns. Some kind of respawning sound would be nice
- **button hover** when hovering a button a small plop sound should be available

Furthermore I noticed some flaws with the existing sounds:
- as you may notice, jumping and landing sounds too clunky (and doesn't fit into the "tron" style game). I had an idea there: similar to [this sound from a previous game](https://github.com/bitbrain/clouboy/blob/master/android/assets/audio/wow.ogg) some kind of "Whew!" voice. However it should sound like a little baby robot and shouldn't be too long. Also the landing sound should be more like a "plop" and should sound lighter.
- obscuring/revealing could be more ambient and less noisy, it's quite dominant at the moment.
- finishing a level could be a little bit more rewarding than a little "bling". I thought it would sound nice but after playing a while I noticed that a simple "bling" feels quite unrewarding.
- death could be changed to a baby robot voice as well. The robot will get a small storyline before playing so I want that the sound gives him some character. No, he hasn't got a name yet :P

**Comment by k0stnix** [comment]
I see what you mean, the jumping and landing sound are actually a bit clunky. I'll try to change them, as soon as I can.

I believe you use the wrong sound for completing a level. Seems to me you picked the "1 up" sound, which is for collecting a life.

There should be a sound called "level_complete", try that one ;)

Also, for some sounds it might sound better, if you fade out the music to have better transitions between sounds. For example, when you get a game over, the level music should fade out while the "game_over" sound starts playing. When it is done playing, the "game_over_screen" music should come in.
